version: "3"

services:
  api:
    image: scoringapp_image
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - FLASK_APP=app/main.py
      - FLASK_DEBUG=1
      - PYTHONUNBUFFERED=1
    volumes:
      - ./app:/app
    entrypoint:
      - flask
      - run
      - --host=0.0.0.0
      - --port=80
    ports:
      - "5005:80"
